#!/bin/bash -ex
docker build -t agorbatchev/dumb-node:8.5.0 -t agorbatchev/dumb-node:latest -t agorbatchev/dumb-node .
docker run -it --rm agorbatchev/dumb-node:latest node -v
docker images | grep "agorbatchev/dumb-node"
